--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/19/2019 10:54:04 AM
-- Server version: 5.5.5-10.3.16-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO admin(id, user_id, username, password, email, name, image, type, date, add_date_time, last_modify, stutus, last_login, last_logout, login_status, website_logo, transaction_pwd) VALUES
(1, 123456, 'admin', '48B1BB7AD34484EF0632D4B9A748CC861DFBE88B', 'kamlesh@maxtratechnologies.net', 'Super Admin', '1441778825main_Ameo_Feature_singleoils_.png', 'admin', '2014-07-27', '2014-06-27 18:15:00', '2014-06-27 07:15:50', 0, '2019-05-06 10:23:21', '2019-05-06 10:30:37', 0, 'icon1410940295logo.png', 'admin'),
(4, 123456, 'admin1', '12345', 'ukmfworld@gmail.com', 'Super Admin', '', 'admin', '0000-00-00', '0000-00-00 00:00:00', '2015-11-01 19:28:00', 0, '2019-02-15 05:39:46', '2019-05-06 10:30:37', 0, 'icon1410940295logo.png', 'admin'),
(8, 20716, 'ashwini', '8c0b6fd0b8380067f30247f0a420f7efcc60df3db8ee90754822b0f87f2d632a', 'hr@ukmf.in', 'ashwini', '', 'sub_admin', '2019-04-24', '2019-04-24 09:48:45', '2019-04-24 09:48:45', 0, '2019-05-30 04:49:18', '0000-00-00 00:00:00', 0, '', '');