--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/19/2019 10:54:06 AM
-- Server version: 5.5.5-10.3.16-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO contactdetail(id, page_name, description, posted_date) VALUES
(15, 'Privacy Policy', 'Coming soon!', '2015-11-03'),
(16, 'Terms and Conditions', 'Coming soon!', '2015-03-26'),
(17, 'Welcome Announcement', '<p>Thanks for register with us !</p>\n', '2015-03-26');