--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/19/2019 10:54:22 AM
-- Server version: 5.5.5-10.3.16-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO promo(news_name, n_id, description, n_date, status, read_viewer, posted_date) VALUES
('Welcome to UK Micro Finance', 7, '<p>Thanks for joining us ! www.ukmicrofinance.in</p>\r\n', '0000-00-00', 1, 1, '2019-02-11 13:19:24');