--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/19/2019 10:54:26 AM
-- Server version: 5.5.5-10.3.16-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sub_admin_category(id, cat_name) VALUES
(1, 'Member Management'),
(2, 'Package Management'),
(3, 'Reports Management'),
(4, 'Ewallet Management'),
(5, 'Withdrawal Management'),
(6, 'Query Tickets Management'),
(7, 'Member Tree '),
(8, 'Settings Management'),
(9, 'Activation Management'),
(10, 'Reports Management'),
(11, 'Staff Management');