--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/19/2019 10:54:27 AM
-- Server version: 5.5.5-10.3.16-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sub_admin_sub_category(id, cat_id, sub_cat_name, link) VALUES
(1, '1', 'Member List', 'member-list.php'),
(3, '1', 'Password Tracker', 'password-tracker.php'),
(4, '1', 'Official Announcement', 'official-announcement.php'),
(5, '2', 'Manage Package', 'manage-package.php'),
(6, '3', 'Sponsor Income', 'sponsor-income-reports.php'),
(7, '3', 'Level Income', 'binary-income-reports.php'),
(13, '4', 'Manage User Ewallet', 'ewallet-management.php'),
(15, '5', 'Open Withdrawal Request', 'open-withdrawal-request.php'),
(16, '5', ' Close Withdrawal Request', 'close-withdrawal-request.php'),
(17, '6', 'Open Ticket Manage', 'open-ticket-manage.php'),
(19, '6', 'Close Ticket Manage', 'close-ticket-manage.php'),
(22, '7', 'Referral Tree', 'direct-member-tree.php'),
(23, '7', 'Team Tree', 'binary-tree.php'),
(24, '8', 'Change Password', 'change-login-password.php'),
(25, '8', 'Change Profile Photo ', 'change-profile-photo.php'),
(26, '8', ' Policy Content Update ', 'content-management.php'),
(29, '3', 'Matching Income', 'matching-income-reports.php'),
(30, '9', 'Pending Payment', 'pending-payment.php'),
(31, '9', 'Approved Payment', 'approved-payment.php'),
(32, '9', 'Cancelled Payment', 'cancelled-payment.php'),
(33, '10', 'Non Working Reward', 'matching-income-reports.php'),
(34, '10', 'Generation Reward', 'matching-income-reports1.php'),
(35, '10', 'Club Reward', 'matching-income-reports2.php'),
(36, '10', 'Direct Member Report', 'direct-member-reports.php'),
(37, '10', 'Downline Member Report', 'downline-member-reports.php'),
(38, '8', 'Subadmin Management', 'sub-admin-manage.php');