--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/19/2019 10:54:33 AM
-- Server version: 5.5.5-10.3.16-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO `withdraw_request-19jan2019`(id, transaction_number, user_id, first_name, last_name, acc_name, acc_number, bank_nm, branch_nm, swift_code, request_amount, description, status, posted_date, admin_remark, admin_response_date, withdraw_wallet, total_paid_amount, transaction_charge) VALUES
(2, '967468', '2018000020180002', 'Achal', 'Singh', 'Achal Singh ', '919628547975 ', 'Paytm Payment Bank', 'NOIDA', 'PYTM0123456', '7407', '. ', 1, '2019-01-10', '<p>i will pay</p>\r\n', '2019-01-10', 'final_e_wallet', '7407', '0'),
(3, '107846', '2018000020180001', 'ishika', 'singh', 'pradeep singh gurjar', '914010017362851', 'axis bank', 'bhopal', 'utib0001048', '1000', 'Withdraw ', 1, '2019-01-10', '<p>i will pay</p>\r\n', '2019-01-10', 'final_e_wallet', '1000', '0'),
(4, '606874', '2018000020180009', 'Meharwan', 'Bhuwaliya', 'Saving', '44528100006371', 'Bank of baroda ', 'Hatpipliya', 'BARB0HATPIP', '1900', 'withdral', 1, '2019-01-10', '<p>i will pay</p>\r\n', '2019-01-10', 'final_e_wallet', '1900', '0'),
(5, '582819', '2018000020180008', 'Muskan', 'Rathore', 'Saving', '995318210019267', 'Bank of india', 'Kurawar', 'Bkid0009953', '738', 'withdral', 1, '2019-01-10', '<p>i will pay</p>\r\n', '2019-01-10', 'final_e_wallet', '738', '0'),
(6, '27298', '2018000020180038', 'Anita', 'Meharvan ', 'Saving', '891718110001879', 'Bank of india', 'Karnawad', 'Bkid0008917', '275', '275', 1, '2019-01-10', '<p>i will pay</p>\r\n', '2019-01-11', 'final_e_wallet', '275', '0'),
(7, '276874', '2018000020180036', 'Rachna', 'Panvar', 'RACHNA PAWAR', '910210510001023', 'BANK OF INDIA ', 'Maxi road ujjain', 'BKID0009102 ', '283', '2018000020180036', 1, '2019-01-10', '<p>i will pay</p>\r\n', '2019-01-11', 'final_e_wallet', '283', '0'),
(8, '821498', '2018000020180003', 'Ramdayal', 'Chouhan', 'Ramdayal singh', '917020032309228', 'Axis bank', 'Lal ghati bhopal', 'UTIB0000569', '360', 'Ramdayal singh', 1, '2019-01-11', '<p>i will pay</p>\r\n', '2019-01-11', 'final_e_wallet', '360', '0'),
(9, '207035', '2018000020180005', 'Sanjeev dixit', 'Sanjeev', 'Sanjeev dixit', '918085802255', 'Paytm payment bank ltd', 'Noida ', 'Pytm0123456', '1900', 'Sanjeev dixit', 1, '2019-01-11', '<p>i will pay</p>\r\n', '2019-01-11', 'final_e_wallet', '1900', '0'),
(10, '125191', '2018000020180098', 'Chandre', 'Prekash', 'Chandra prakash gound', '31874292827', 'SBI', 'Ring road Bombay hospital indore', 'SBIN0030463', '412', 'Chandra prakash', 1, '2019-01-11', '<p>i will pay</p>\r\n', '2019-01-12', 'final_e_wallet', '412', '0'),
(11, '171971', '2018000020180009', 'Meharwan', 'Bhuwaliya', 'Saving', '44528100006371', 'Bank of baroda ', 'Hatpipliya', 'BARB0HATPIP', '3200', 'Meharban', 1, '2019-01-11', '<p>i will pay</p>\r\n', '2019-01-12', 'final_e_wallet', '3200', '0'),
(12, '291331', '2018000020180053', 'Bhagwat. ', 'Singh', 'Saving', '14900110021262', 'Uco bank', 'Bhopal', 'Ucba0001490', '627', 'Bhagwat', 1, '2019-01-11', '<p>i will pay</p>\r\n', '2019-01-12', 'final_e_wallet', '627', '0'),
(13, '991401', '2018000020180093', 'Dharm ', 'Singh', 'Saving', '688002010000216', 'Union bank', 'Nimbaheda', 'UBIN0568805', '1000', 'Dharamsingji', 1, '2019-01-11', '<p>i will pay</p>\r\n', '2019-01-12', 'final_e_wallet', '1000', '0'),
(14, '38854', '2018000020180054', 'Govind ', 'Chouhan', 'govind singh chouhan', '53040058529', 'sbi', 'kurawar', 'sbin0030459', '370', '12345', 1, '2019-01-14', '', '2019-01-17', 'final_e_wallet', '370', '0'),
(15, '157033', '2018000020180031', 'Nilesh ', 'Dhakar ', '', '', '', '', '', '670', 'Pls transfer this amount ', 1, '2019-01-14', '', '2019-01-17', 'final_e_wallet', '670', '0'),
(16, '919278', '2018000020180016', 'Suresh', 'Meena', 'Suresh kumar meena', '995810110012687', 'Bank of India', 'Narsinghgarh', 'Bkid0009958', '400', 'SureshMeena', 1, '2019-01-15', '', '2019-01-17', 'final_e_wallet', '400', '0'),
(17, '396106', '2018000020180266', 'SUSHIL', 'KUMAR RAI', 'SUSHIL KUMAR RAI ', '0649010061778', 'UNITED BANK OF INDIA ', 'BHOPAL', 'UTBI0BPL624', '450', '2018000020180266', 1, '2019-01-16', '', '2019-01-17', 'final_e_wallet', '450', '0'),
(18, '291179', '2018000020180214', 'Lokesh', 'meena', 'LOKESH MEENA ', '31662194537', 'STATE BANK OF INDIA ', 'MURALI NAGAR BERASIYA ROAD BHOPAL ', 'SBIN0030514 ', '500', '2018000020180214', 1, '2019-01-16', '', '2019-01-17', 'final_e_wallet', '500', '0'),
(19, '444164', '2018000020180019', 'hindu', 'singh', 'hindu singh', '918020002032366', 'axis bank', 'lal ghati bhopal', 'utib0000569', '960', 'Hindu singh', 1, '2019-01-16', '', '2019-01-17', 'final_e_wallet', '960', '0'),
(20, '880984', '2018000020180106', 'Solanki ', 'Jivanlal', 'Saving', '276410110000365', 'Bank Of India', 'VEDNAGAR', 'BKID0009110', '400', '12345', 1, '2019-01-17', '', '2019-01-17', 'final_e_wallet', '400', '0'),
(21, '614234', '2018000020180015', 'Hemlata', 'Sharma', 'HemlataSharma', '33972038626', 'SBI', 'Narsinghgarh', 'Sbin0010809', '1594', 'Hemlata Sharma', 1, '2019-01-17', '', '2019-01-17', 'final_e_wallet', '1594', '0'),
(22, '941104', '2018000020180024', 'kaushal', 'vyas', 'Kaushal Vyas', '6731101000130', 'Canara Bank ', 'Phoolbag, Narsinghgarh', 'CNRB0006731', '1400', 'Kaushal', 1, '2019-01-17', '', '2019-01-17', 'final_e_wallet', '1400', '0');